name: omni_label
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # google_mlkit_text_recognition: ^0.13.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_scalable_ocr: ^2.0.0
  barcode: ^2.2.8
  flutter_svg: ^2.0.10+1
  flutter_flip_card: ^0.0.6
  app_links: ^6.2.1
   # ocr_scan_text: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0

flutter:

  
  
  
  uses-material-design: true


# Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision 761747bfc5 (3 months ago) • 2024-06-05 22:15:13 +0200
# Engine • revision edd8546116
# Tools • Dart 3.4.3 • DevTools 2.34.3